// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from "./client";
import type {
  StatusData,
  StatusResponses,
  SetupData,
  SetupResponses,
  SetupErrors,
  LoginData,
  LoginResponses,
  LoginErrors,
  RefreshData,
  RefreshResponses,
  RefreshErrors,
  LogoutData,
  LogoutResponses,
  LogoutErrors,
  MeData,
  MeResponses,
  ForgotPasswordData,
  ForgotPasswordResponses,
  ForgotPasswordErrors,
  ResetPasswordData,
  ResetPasswordResponses,
  ResetPasswordErrors,
  ListTokensData,
  ListTokensResponses,
  CreateTokenData,
  CreateTokenResponses,
  CreateTokenErrors,
  RevokeTokenData,
  RevokeTokenResponses,
  RevokeTokenErrors,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Auth {
  /**
   * Status
   * Whether the archive still needs its first admin (the sign-in page shows the setup form instead).
   */
  public static status<ThrowOnError extends boolean = false>(
    options?: Options<StatusData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      StatusResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/v1/auth/status",
      ...options,
    });
  }

  /**
   * Setup
   * Create the first admin with the one-time code printed in the server log.
   */
  public static setup<ThrowOnError extends boolean = false>(
    options: Options<SetupData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      SetupResponses,
      SetupErrors,
      ThrowOnError
    >({
      url: "/api/v1/auth/setup",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Login
   */
  public static login<ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LoginResponses,
      LoginErrors,
      ThrowOnError
    >({
      url: "/api/v1/auth/login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Refresh
   * Swap a refresh token for a new pair. Each refresh token works once.
   */
  public static refresh<ThrowOnError extends boolean = false>(
    options: Options<RefreshData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      RefreshResponses,
      RefreshErrors,
      ThrowOnError
    >({
      url: "/api/v1/auth/refresh",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Logout
   */
  public static logout<ThrowOnError extends boolean = false>(
    options: Options<LogoutData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LogoutResponses,
      LogoutErrors,
      ThrowOnError
    >({
      url: "/api/v1/auth/logout",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Me
   */
  public static me<ThrowOnError extends boolean = false>(
    options?: Options<MeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
      url: "/api/v1/auth/me",
      ...options,
    });
  }

  /**
   * Forgot Password
   * Email a reset link. Answers the same whether or not the address has an account.
   */
  public static forgotPassword<ThrowOnError extends boolean = false>(
    options: Options<ForgotPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      ForgotPasswordResponses,
      ForgotPasswordErrors,
      ThrowOnError
    >({
      url: "/api/v1/auth/password/forgot",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Reset Password
   */
  public static resetPassword<ThrowOnError extends boolean = false>(
    options: Options<ResetPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      ResetPasswordResponses,
      ResetPasswordErrors,
      ThrowOnError
    >({
      url: "/api/v1/auth/password/reset",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Tokens {
  /**
   * List Tokens
   */
  public static listTokens<ThrowOnError extends boolean = false>(
    options?: Options<ListTokensData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ListTokensResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/v1/tokens",
      ...options,
    });
  }

  /**
   * Create Token
   */
  public static createToken<ThrowOnError extends boolean = false>(
    options: Options<CreateTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateTokenResponses,
      CreateTokenErrors,
      ThrowOnError
    >({
      url: "/api/v1/tokens",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Revoke Token
   */
  public static revokeToken<ThrowOnError extends boolean = false>(
    options: Options<RevokeTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      RevokeTokenResponses,
      RevokeTokenErrors,
      ThrowOnError
    >({
      url: "/api/v1/tokens/{token_id}",
      ...options,
    });
  }
}
