// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from "./client";
import type {
  StatusData,
  StatusResponses,
  SetupData,
  SetupResponses,
  SetupErrors,
  LoginData,
  LoginResponses,
  LoginErrors,
  RefreshData,
  RefreshResponses,
  RefreshErrors,
  LogoutData,
  LogoutResponses,
  LogoutErrors,
  MeData,
  MeResponses,
  ForgotPasswordData,
  ForgotPasswordResponses,
  ForgotPasswordErrors,
  ResetPasswordData,
  ResetPasswordResponses,
  ResetPasswordErrors,
  ListTokensData,
  ListTokensResponses,
  CreateTokenData,
  CreateTokenResponses,
  CreateTokenErrors,
  RevokeTokenData,
  RevokeTokenResponses,
  RevokeTokenErrors,
  ListUsersData,
  ListUsersResponses,
  CreateUserData,
  CreateUserResponses,
  CreateUserErrors,
  UpdateUserData,
  UpdateUserResponses,
  UpdateUserErrors,
  ListMembersData,
  ListMembersResponses,
  ListMembersErrors,
  SetMemberData,
  SetMemberResponses,
  SetMemberErrors,
  GetSettingsData,
  GetSettingsResponses,
  UpdateSettingsData,
  UpdateSettingsResponses,
  UpdateSettingsErrors,
  TestLlmData,
  TestLlmResponses,
  ListAuditData,
  ListAuditResponses,
  ListAuditErrors,
  GetHealthData,
  GetHealthResponses,
  ReindexSearchData,
  ReindexSearchResponses,
  ListNamespacesData,
  ListNamespacesResponses,
  CreateNamespaceData,
  CreateNamespaceResponses,
  CreateNamespaceErrors,
  UpdateNamespaceData,
  UpdateNamespaceResponses,
  UpdateNamespaceErrors,
  GetNamespaceWordcloudData,
  GetNamespaceWordcloudResponses,
  GetNamespaceWordcloudErrors,
  ListIpGroupsData,
  ListIpGroupsResponses,
  ListIpGroupsErrors,
  CreateIpGroupData,
  CreateIpGroupResponses,
  CreateIpGroupErrors,
  DeleteIpGroupData,
  DeleteIpGroupResponses,
  DeleteIpGroupErrors,
  UpdateIpGroupData,
  UpdateIpGroupResponses,
  UpdateIpGroupErrors,
  ListRecordingsData,
  ListRecordingsResponses,
  ListRecordingsErrors,
  GetRecordingData,
  GetRecordingResponses,
  GetRecordingErrors,
  UpdateRecordingData,
  UpdateRecordingResponses,
  UpdateRecordingErrors,
  GetRecordingAccessData,
  GetRecordingAccessResponses,
  GetRecordingAccessErrors,
  UpdateRecordingAccessData,
  UpdateRecordingAccessResponses,
  UpdateRecordingAccessErrors,
  ListRecordingPermissionsData,
  ListRecordingPermissionsResponses,
  ListRecordingPermissionsErrors,
  AddRecordingPermissionData,
  AddRecordingPermissionResponses,
  AddRecordingPermissionErrors,
  RemoveRecordingPermissionData,
  RemoveRecordingPermissionResponses,
  RemoveRecordingPermissionErrors,
  ListRecordingIpGroupsData,
  ListRecordingIpGroupsResponses,
  ListRecordingIpGroupsErrors,
  CloseRecordingToIpGroupData,
  CloseRecordingToIpGroupResponses,
  CloseRecordingToIpGroupErrors,
  OpenRecordingToIpGroupData,
  OpenRecordingToIpGroupResponses,
  OpenRecordingToIpGroupErrors,
  ListAccessRequestsData,
  ListAccessRequestsResponses,
  ListAccessRequestsErrors,
  ApproveAccessRequestData,
  ApproveAccessRequestResponses,
  ApproveAccessRequestErrors,
  DeclineAccessRequestData,
  DeclineAccessRequestResponses,
  DeclineAccessRequestErrors,
  GetPlayerData,
  GetPlayerResponses,
  GetPlayerErrors,
  GetEmbedLinkData,
  GetEmbedLinkResponses,
  GetEmbedLinkErrors,
  GetAudioData,
  GetAudioResponses,
  GetAudioErrors,
  GetRecordingWordcloudData,
  GetRecordingWordcloudResponses,
  GetRecordingWordcloudErrors,
  ReprocessRecordingData,
  ReprocessRecordingResponses,
  ReprocessRecordingErrors,
  RevokeSharesData,
  RevokeSharesResponses,
  RevokeSharesErrors,
  CreateShareData,
  CreateShareResponses,
  CreateShareErrors,
  ListSharesData,
  ListSharesResponses,
  ListSharesErrors,
  ExportRecordingData,
  ExportRecordingResponses,
  ExportRecordingErrors,
  EditSegmentData,
  EditSegmentResponses,
  EditSegmentErrors,
  ListSegmentEditsData,
  ListSegmentEditsResponses,
  ListSegmentEditsErrors,
  ListOutputsData,
  ListOutputsResponses,
  ListOutputsErrors,
  ImportTranscriptData,
  ImportTranscriptResponses,
  ImportTranscriptErrors,
  PreviewImportData,
  PreviewImportResponses,
  PreviewImportErrors,
  SearchTranscriptsData,
  SearchTranscriptsResponses,
  SearchTranscriptsErrors,
  GetGraphData,
  GetGraphResponses,
  GetGraphErrors,
  ListMentionsData,
  ListMentionsResponses,
  ListMentionsErrors,
  ListSpeakersData,
  ListSpeakersResponses,
  ListSpeakersErrors,
  ListSpeakerRecordingsData,
  ListSpeakerRecordingsResponses,
  ListSpeakerRecordingsErrors,
  RenameSpeakerData,
  RenameSpeakerResponses,
  RenameSpeakerErrors,
  MergeSpeakerData,
  MergeSpeakerResponses,
  MergeSpeakerErrors,
  UndoSpeakerMergeData,
  UndoSpeakerMergeResponses,
  UndoSpeakerMergeErrors,
  LinkSpeakerData,
  LinkSpeakerResponses,
  LinkSpeakerErrors,
  ListEntitiesData,
  ListEntitiesResponses,
  ListEntitiesErrors,
  ListEntityTypesData,
  ListEntityTypesResponses,
  ListEntitySuggestionsData,
  ListEntitySuggestionsResponses,
  ListEntitySuggestionsErrors,
  ListEntityMergesData,
  ListEntityMergesResponses,
  GetEntityTimelineData,
  GetEntityTimelineResponses,
  GetEntityTimelineErrors,
  RetypeEntitiesData,
  RetypeEntitiesResponses,
  RetypeEntitiesErrors,
  MergeEntitiesData,
  MergeEntitiesResponses,
  MergeEntitiesErrors,
  UndoEntityMergeData,
  UndoEntityMergeResponses,
  UndoEntityMergeErrors,
  MarkEntitiesNotSameData,
  MarkEntitiesNotSameResponses,
  MarkEntitiesNotSameErrors,
  GetEntityData,
  GetEntityResponses,
  GetEntityErrors,
  ListEntityMentionsData,
  ListEntityMentionsResponses,
  ListEntityMentionsErrors,
  GetEntityConnectionsData,
  GetEntityConnectionsResponses,
  GetEntityConnectionsErrors,
  RenameEntityData,
  RenameEntityResponses,
  RenameEntityErrors,
  HideEntityData,
  HideEntityResponses,
  HideEntityErrors,
  LinkEntityData,
  LinkEntityResponses,
  LinkEntityErrors,
  UnlinkEntityData,
  UnlinkEntityResponses,
  UnlinkEntityErrors,
  MoveMentionData,
  MoveMentionResponses,
  MoveMentionErrors,
  ExploreGraphData,
  ExploreGraphResponses,
  ExploreGraphErrors,
  FindGraphPathData,
  FindGraphPathResponses,
  FindGraphPathErrors,
  GetRecordingMetadataData,
  GetRecordingMetadataResponses,
  GetRecordingMetadataErrors,
  UpdateRecordingMetadataData,
  UpdateRecordingMetadataResponses,
  UpdateRecordingMetadataErrors,
  ListRecordingMetadataHistoryData,
  ListRecordingMetadataHistoryResponses,
  ListRecordingMetadataHistoryErrors,
  RevertMetadataEditData,
  RevertMetadataEditResponses,
  RevertMetadataEditErrors,
  GetNamespaceMetadataData,
  GetNamespaceMetadataResponses,
  GetNamespaceMetadataErrors,
  UpdateNamespaceMetadataData,
  UpdateNamespaceMetadataResponses,
  UpdateNamespaceMetadataErrors,
  BulkUpdateMetadataData,
  BulkUpdateMetadataResponses,
  BulkUpdateMetadataErrors,
  GetMediaData,
  GetMediaResponses,
  GetMediaErrors,
  GetFrameData,
  GetFrameResponses,
  GetFrameErrors,
  FixScreenTextData,
  FixScreenTextResponses,
  FixScreenTextErrors,
  DeleteFaceTrackData,
  DeleteFaceTrackResponses,
  DeleteFaceTrackErrors,
  DeleteNamespaceFacesData,
  DeleteNamespaceFacesResponses,
  DeleteNamespaceFacesErrors,
  GetNamespaceFacesData,
  GetNamespaceFacesResponses,
  GetNamespaceFacesErrors,
  SetNamespaceFacesModeData,
  SetNamespaceFacesModeResponses,
  SetNamespaceFacesModeErrors,
  UndoFaceMergeData,
  UndoFaceMergeResponses,
  UndoFaceMergeErrors,
  DeleteFaceData,
  DeleteFaceResponses,
  DeleteFaceErrors,
  RenameFaceData,
  RenameFaceResponses,
  RenameFaceErrors,
  MergeFaceData,
  MergeFaceResponses,
  MergeFaceErrors,
  LinkFaceSpeakerData,
  LinkFaceSpeakerResponses,
  LinkFaceSpeakerErrors,
  DismissFaceSuggestionData,
  DismissFaceSuggestionResponses,
  DismissFaceSuggestionErrors,
  GetRecordingIiifData,
  GetRecordingIiifResponses,
  GetRecordingIiifErrors,
  GetContentStateData,
  GetContentStateResponses,
  GetContentStateErrors,
  PreviewIiifImportData,
  PreviewIiifImportResponses,
  PreviewIiifImportErrors,
  ImportIiifData,
  ImportIiifResponses,
  ImportIiifErrors,
  ListJobsData,
  ListJobsResponses,
  ListJobsErrors,
  CreateJobsData,
  CreateJobsResponses,
  CreateJobsErrors,
  GetJobData,
  GetJobResponses,
  GetJobErrors,
  QueueStepData,
  QueueStepResponses,
  QueueStepErrors,
  CancelJobData,
  CancelJobResponses,
  CancelJobErrors,
  RetryJobData,
  RetryJobResponses,
  RetryJobErrors,
  ListWorkersData,
  ListWorkersResponses,
  StreamEventsData,
  StreamEventsResponses,
  StreamEventsErrors,
  ListBackendsData,
  ListBackendsResponses,
  ListSourcesData,
  ListSourcesResponses,
  CreateSourceData,
  CreateSourceResponses,
  CreateSourceErrors,
  DeleteSourceData,
  DeleteSourceResponses,
  DeleteSourceErrors,
  UpdateSourceData,
  UpdateSourceResponses,
  UpdateSourceErrors,
  TestSourceData,
  TestSourceResponses,
  TestSourceErrors,
  BrowseSourceData,
  BrowseSourceResponses,
  BrowseSourceErrors,
  ListWatchesData,
  ListWatchesResponses,
  CreateWatchData,
  CreateWatchResponses,
  CreateWatchErrors,
  PreviewWatchData,
  PreviewWatchResponses,
  PreviewWatchErrors,
  DeleteWatchData,
  DeleteWatchResponses,
  DeleteWatchErrors,
  UpdateWatchData,
  UpdateWatchResponses,
  UpdateWatchErrors,
  ScanWatchData,
  ScanWatchResponses,
  ScanWatchErrors,
  ListTemplatesData,
  ListTemplatesResponses,
  CreateTemplateData,
  CreateTemplateResponses,
  CreateTemplateErrors,
  PreviewTemplateData,
  PreviewTemplateResponses,
  PreviewTemplateErrors,
  GetTemplateData,
  GetTemplateResponses,
  GetTemplateErrors,
  CreateTemplateVersionData,
  CreateTemplateVersionResponses,
  CreateTemplateVersionErrors,
  DiffTemplateVersionsData,
  DiffTemplateVersionsResponses,
  DiffTemplateVersionsErrors,
  ListPipelinesData,
  ListPipelinesResponses,
  CreatePipelineData,
  CreatePipelineResponses,
  CreatePipelineErrors,
  GetPipelineData,
  GetPipelineResponses,
  GetPipelineErrors,
  CreatePipelineVersionData,
  CreatePipelineVersionResponses,
  CreatePipelineVersionErrors,
  RunPipelineData,
  RunPipelineResponses,
  RunPipelineErrors,
  ListChatsData,
  ListChatsResponses,
  CreateChatData,
  CreateChatResponses,
  CreateChatErrors,
  DeleteChatData,
  DeleteChatResponses,
  DeleteChatErrors,
  GetChatData,
  GetChatResponses,
  GetChatErrors,
  UpdateChatData,
  UpdateChatResponses,
  UpdateChatErrors,
  SendMessageData,
  SendMessageResponses,
  SendMessageErrors,
  CheckMessageData,
  CheckMessageResponses,
  CheckMessageErrors,
  ListApprovalsData,
  ListApprovalsResponses,
  ListApprovalsErrors,
  DecideApprovalData,
  DecideApprovalResponses,
  DecideApprovalErrors,
  ListCollectionsData,
  ListCollectionsResponses,
  CreateCollectionData,
  CreateCollectionResponses,
  CreateCollectionErrors,
  DeleteCollectionData,
  DeleteCollectionResponses,
  DeleteCollectionErrors,
  GetCollectionData,
  GetCollectionResponses,
  GetCollectionErrors,
  UpdateCollectionData,
  UpdateCollectionResponses,
  UpdateCollectionErrors,
  EstimateBatchData,
  EstimateBatchResponses,
  EstimateBatchErrors,
  ListBatchesData,
  ListBatchesResponses,
  CreateBatchData,
  CreateBatchResponses,
  CreateBatchErrors,
  GetBatchData,
  GetBatchResponses,
  GetBatchErrors,
  CombineBatchData,
  CombineBatchResponses,
  CombineBatchErrors,
  ControlBatchData,
  ControlBatchResponses,
  ControlBatchErrors,
  GetBatchResultsData,
  GetBatchResultsResponses,
  GetBatchResultsErrors,
  ExportBatchResultsData,
  ExportBatchResultsResponses,
  ExportBatchResultsErrors,
  GetPublicHomeData,
  GetPublicHomeResponses,
  GetPublicCollectionData,
  GetPublicCollectionResponses,
  GetPublicCollectionErrors,
  SearchPublicData,
  SearchPublicResponses,
  SearchPublicErrors,
  GetPublicRecordingData,
  GetPublicRecordingResponses,
  GetPublicRecordingErrors,
  RequestAccessData,
  RequestAccessResponses,
  RequestAccessErrors,
  ListPendingAccessRequestsData,
  ListPendingAccessRequestsResponses,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Auth {
  /**
   * Status
   * Whether the archive still needs its first admin (the sign-in page shows the setup form instead).
   */
  public static status<ThrowOnError extends boolean = false>(options?: Options<StatusData, ThrowOnError>) {
    return (options?.client ?? client).get<StatusResponses, unknown, ThrowOnError>({
      url: "/api/v1/auth/status",
      ...options,
    });
  }

  /**
   * Setup
   * Create the first admin with the one-time code printed in the server log.
   */
  public static setup<ThrowOnError extends boolean = false>(options: Options<SetupData, ThrowOnError>) {
    return (options.client ?? client).post<SetupResponses, SetupErrors, ThrowOnError>({
      url: "/api/v1/auth/setup",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Login
   */
  public static login<ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) {
    return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
      url: "/api/v1/auth/login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Refresh
   * Swap a refresh token for a new pair. Each refresh token works once.
   */
  public static refresh<ThrowOnError extends boolean = false>(options: Options<RefreshData, ThrowOnError>) {
    return (options.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({
      url: "/api/v1/auth/refresh",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Logout
   */
  public static logout<ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>) {
    return (options.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
      url: "/api/v1/auth/logout",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Me
   */
  public static me<ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) {
    return (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
      url: "/api/v1/auth/me",
      ...options,
    });
  }

  /**
   * Forgot Password
   * Email a reset link. Answers the same whether or not the address has an account.
   */
  public static forgotPassword<ThrowOnError extends boolean = false>(
    options: Options<ForgotPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ForgotPasswordResponses, ForgotPasswordErrors, ThrowOnError>({
      url: "/api/v1/auth/password/forgot",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Reset Password
   */
  public static resetPassword<ThrowOnError extends boolean = false>(options: Options<ResetPasswordData, ThrowOnError>) {
    return (options.client ?? client).post<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError>({
      url: "/api/v1/auth/password/reset",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Tokens {
  /**
   * List Tokens
   */
  public static listTokens<ThrowOnError extends boolean = false>(options?: Options<ListTokensData, ThrowOnError>) {
    return (options?.client ?? client).get<ListTokensResponses, unknown, ThrowOnError>({
      url: "/api/v1/tokens",
      ...options,
    });
  }

  /**
   * Create Token
   */
  public static createToken<ThrowOnError extends boolean = false>(options: Options<CreateTokenData, ThrowOnError>) {
    return (options.client ?? client).post<CreateTokenResponses, CreateTokenErrors, ThrowOnError>({
      url: "/api/v1/tokens",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Revoke Token
   */
  public static revokeToken<ThrowOnError extends boolean = false>(options: Options<RevokeTokenData, ThrowOnError>) {
    return (options.client ?? client).delete<RevokeTokenResponses, RevokeTokenErrors, ThrowOnError>({
      url: "/api/v1/tokens/{token_id}",
      ...options,
    });
  }
}

export class Users {
  /**
   * List Users
   * Every account, with its role in each namespace.
   */
  public static listUsers<ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>) {
    return (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
      url: "/api/v1/users",
      ...options,
    });
  }

  /**
   * Create User
   */
  public static createUser<ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) {
    return (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
      url: "/api/v1/users",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Update User
   * Rename, promote or demote, disable, or set a new password (which signs the person out everywhere).
   */
  public static updateUser<ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
      url: "/api/v1/users/{uid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * List Members
   * Who has a role in this namespace (owners only).
   */
  public static listMembers<ThrowOnError extends boolean = false>(options: Options<ListMembersData, ThrowOnError>) {
    return (options.client ?? client).get<ListMembersResponses, ListMembersErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/members",
      ...options,
    });
  }

  /**
   * Set Member
   * Give someone a role in this namespace, change it, or (role null) remove them. Owners only.
   */
  public static setMember<ThrowOnError extends boolean = false>(options: Options<SetMemberData, ThrowOnError>) {
    return (options.client ?? client).put<SetMemberResponses, SetMemberErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/members",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Admin {
  /**
   * Get Settings
   * Every section people can change in the app, with who changed it last. Secrets show only whether they are set.
   */
  public static getSettings<ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) {
    return (options?.client ?? client).get<GetSettingsResponses, unknown, ThrowOnError>({
      url: "/api/v1/settings",
      ...options,
    });
  }

  /**
   * Update Settings
   * Change some settings in one section; the keys and their types are checked against the section's defaults.
   */
  public static updateSettings<ThrowOnError extends boolean = false>(
    options: Options<UpdateSettingsData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError>({
      url: "/api/v1/settings/{section}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Test Llm
   * Ask the configured model for one word, to check the address, key and model name.
   */
  public static testLlm<ThrowOnError extends boolean = false>(options?: Options<TestLlmData, ThrowOnError>) {
    return (options?.client ?? client).post<TestLlmResponses, unknown, ThrowOnError>({
      url: "/api/v1/settings/llm/test",
      ...options,
    });
  }

  /**
   * List Audit
   * Who changed what, newest first.
   */
  public static listAudit<ThrowOnError extends boolean = false>(options?: Options<ListAuditData, ThrowOnError>) {
    return (options?.client ?? client).get<ListAuditResponses, ListAuditErrors, ThrowOnError>({
      url: "/api/v1/audit",
      ...options,
    });
  }

  /**
   * Get Health
   * The database, the job queue, workers, storage sources and disk space at a glance.
   */
  public static getHealth<ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) {
    return (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
      url: "/api/v1/admin/health",
      ...options,
    });
  }

  /**
   * Reindex Search
   * Rebuild the search index in the background.
   */
  public static reindexSearch<ThrowOnError extends boolean = false>(
    options?: Options<ReindexSearchData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<ReindexSearchResponses, unknown, ThrowOnError>({
      url: "/api/v1/admin/reindex",
      ...options,
    });
  }
}

export class Namespaces {
  /**
   * List Namespaces
   */
  public static listNamespaces<ThrowOnError extends boolean = false>(
    options?: Options<ListNamespacesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListNamespacesResponses, unknown, ThrowOnError>({
      url: "/api/v1/namespaces",
      ...options,
    });
  }

  /**
   * Create Namespace
   */
  public static createNamespace<ThrowOnError extends boolean = false>(
    options: Options<CreateNamespaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateNamespaceResponses, CreateNamespaceErrors, ThrowOnError>({
      url: "/api/v1/namespaces",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Update Namespace
   * Owners: the graph mode (shared or isolated) and the default pipeline (null for the built-in one).
   */
  public static updateNamespace<ThrowOnError extends boolean = false>(
    options: Options<UpdateNamespaceData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<UpdateNamespaceResponses, UpdateNamespaceErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Namespace Wordcloud
   * The namespace's word cloud. Accepts a bearer token or the signed link from the namespace list.
   */
  public static getNamespaceWordcloud<ThrowOnError extends boolean = false>(
    options: Options<GetNamespaceWordcloudData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetNamespaceWordcloudResponses, GetNamespaceWordcloudErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/wordcloud.svg",
      ...options,
    });
  }

  /**
   * List Ip Groups
   * The namespace's IP groups (owners), and your address as the server sees it, to check the ranges against.
   */
  public static listIpGroups<ThrowOnError extends boolean = false>(options: Options<ListIpGroupsData, ThrowOnError>) {
    return (options.client ?? client).get<ListIpGroupsResponses, ListIpGroupsErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/ip-groups",
      ...options,
    });
  }

  /**
   * Create Ip Group
   * Add an IP group (owners): visitors from its addresses see all of every recording in the namespace
   * (everything), or of the recordings chosen on each. Answers with all of the namespace's groups.
   */
  public static createIpGroup<ThrowOnError extends boolean = false>(options: Options<CreateIpGroupData, ThrowOnError>) {
    return (options.client ?? client).post<CreateIpGroupResponses, CreateIpGroupErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/ip-groups",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Ip Group
   * Delete an IP group (owners): its visitors lose what it opened. Answers with the groups left.
   */
  public static deleteIpGroup<ThrowOnError extends boolean = false>(options: Options<DeleteIpGroupData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteIpGroupResponses, DeleteIpGroupErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/ip-groups/{gid}",
      ...options,
    });
  }

  /**
   * Update Ip Group
   * Rename an IP group, change its ranges or what it opens (owners). Choosing recordings again after opening
   * everything brings back the ones chosen before.
   */
  public static updateIpGroup<ThrowOnError extends boolean = false>(options: Options<UpdateIpGroupData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdateIpGroupResponses, UpdateIpGroupErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/ip-groups/{gid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Recordings {
  /**
   * List Recordings
   * Recordings you can read, newest first by default. Filters combine with AND; the ``X-Total-Count`` header says how many
   * match in all, so pages can be counted.
   */
  public static listRecordings<ThrowOnError extends boolean = false>(
    options?: Options<ListRecordingsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListRecordingsResponses, ListRecordingsErrors, ThrowOnError>({
      url: "/api/v1/recordings",
      ...options,
    });
  }

  /**
   * Get Recording
   */
  public static getRecording<ThrowOnError extends boolean = false>(options: Options<GetRecordingData, ThrowOnError>) {
    return (options.client ?? client).get<GetRecordingResponses, GetRecordingErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}",
      ...options,
    });
  }

  /**
   * Update Recording
   * Rename a recording (editors). Its report is rebuilt with the new title.
   */
  public static updateRecording<ThrowOnError extends boolean = false>(
    options: Options<UpdateRecordingData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<UpdateRecordingResponses, UpdateRecordingErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Recording Access
   * Who may see the recording: public, restricted or private, the parts a public one opens, featured.
   */
  public static getRecordingAccess<ThrowOnError extends boolean = false>(
    options: Options<GetRecordingAccessData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetRecordingAccessResponses, GetRecordingAccessErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/access",
      ...options,
    });
  }

  /**
   * Update Recording Access
   * Make a recording public, restricted or private, choose what a public one opens, feature it (owners).
   *
   * access or open set to null follow the namespace's default again. The change is kept in the metadata history, and
   * IIIF harvesters hear when the recording is published, changed or withdrawn.
   */
  public static updateRecordingAccess<ThrowOnError extends boolean = false>(
    options: Options<UpdateRecordingAccessData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateRecordingAccessResponses, UpdateRecordingAccessErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/access",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * List Recording Permissions
   * The people given permission on the recording (owners), newest first.
   */
  public static listRecordingPermissions<ThrowOnError extends boolean = false>(
    options: Options<ListRecordingPermissionsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      ListRecordingPermissionsResponses,
      ListRecordingPermissionsErrors,
      ThrowOnError
    >({
      url: "/api/v1/recordings/{rid}/permissions",
      ...options,
    });
  }

  /**
   * Add Recording Permission
   * Give someone with an account permission on the recording (owners): they see all of it on the pages visitors see
   * and in IIIF, whatever its access; members of its namespace already do. Answers with everyone who has permission.
   */
  public static addRecordingPermission<ThrowOnError extends boolean = false>(
    options: Options<AddRecordingPermissionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<AddRecordingPermissionResponses, AddRecordingPermissionErrors, ThrowOnError>(
      {
        url: "/api/v1/recordings/{rid}/permissions",
        ...options,
        headers: {
          "Content-Type": "application/json",
          ...options.headers,
        },
      },
    );
  }

  /**
   * Remove Recording Permission
   * Take someone's permission on the recording away (owners). Answers with everyone who still has it.
   */
  public static removeRecordingPermission<ThrowOnError extends boolean = false>(
    options: Options<RemoveRecordingPermissionData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      RemoveRecordingPermissionResponses,
      RemoveRecordingPermissionErrors,
      ThrowOnError
    >({
      url: "/api/v1/recordings/{rid}/permissions/{account}",
      ...options,
    });
  }

  /**
   * List Recording Ip Groups
   * The namespace's IP groups (owners), each with whether visitors from its addresses see all of this recording.
   */
  public static listRecordingIpGroups<ThrowOnError extends boolean = false>(
    options: Options<ListRecordingIpGroupsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListRecordingIpGroupsResponses, ListRecordingIpGroupsErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/ip-groups",
      ...options,
    });
  }

  /**
   * Close Recording To Ip Group
   * Close the recording to an IP group again (owners).
   */
  public static closeRecordingToIpGroup<ThrowOnError extends boolean = false>(
    options: Options<CloseRecordingToIpGroupData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      CloseRecordingToIpGroupResponses,
      CloseRecordingToIpGroupErrors,
      ThrowOnError
    >({
      url: "/api/v1/recordings/{rid}/ip-groups/{gid}",
      ...options,
    });
  }

  /**
   * Open Recording To Ip Group
   * Open the recording to an IP group that opens chosen recordings (owners): visitors from its addresses see all of
   * it. Answers with the namespace's groups.
   */
  public static openRecordingToIpGroup<ThrowOnError extends boolean = false>(
    options: Options<OpenRecordingToIpGroupData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<OpenRecordingToIpGroupResponses, OpenRecordingToIpGroupErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/ip-groups/{gid}",
      ...options,
    });
  }

  /**
   * List Access Requests
   * Requests for access to the recording (owners), newest first; pending ones wait for an answer.
   */
  public static listAccessRequests<ThrowOnError extends boolean = false>(
    options: Options<ListAccessRequestsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListAccessRequestsResponses, ListAccessRequestsErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/requests",
      ...options,
    });
  }

  /**
   * Approve Access Request
   * Approve a request (owners): the person gets permission on the recording.
   */
  public static approveAccessRequest<ThrowOnError extends boolean = false>(
    options: Options<ApproveAccessRequestData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ApproveAccessRequestResponses, ApproveAccessRequestErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/requests/{account}/approve",
      ...options,
    });
  }

  /**
   * Decline Access Request
   * Decline a request (owners). They can ask again.
   */
  public static declineAccessRequest<ThrowOnError extends boolean = false>(
    options: Options<DeclineAccessRequestData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<DeclineAccessRequestResponses, DeclineAccessRequestErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/requests/{account}/decline",
      ...options,
    });
  }

  /**
   * Get Player
   * Player data. Works with a share link (``?s=``) as well as signed in; media links in it are signed.
   */
  public static getPlayer<ThrowOnError extends boolean = false>(options: Options<GetPlayerData, ThrowOnError>) {
    return (options.client ?? client).get<GetPlayerResponses, GetPlayerErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/player",
      ...options,
    });
  }

  /**
   * Get Embed Link
   * A signed link to the embeddable player, for people who can see the recording (it expires; share links don't).
   */
  public static getEmbedLink<ThrowOnError extends boolean = false>(options: Options<GetEmbedLinkData, ThrowOnError>) {
    return (options.client ?? client).get<GetEmbedLinkResponses, GetEmbedLinkErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/embed-link",
      ...options,
    });
  }

  /**
   * Get Audio
   * The audio, with byte ranges. Accepts a bearer token, a share link (``?s=``) or a signed link.
   */
  public static getAudio<ThrowOnError extends boolean = false>(options: Options<GetAudioData, ThrowOnError>) {
    return (options.client ?? client).get<GetAudioResponses, GetAudioErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/audio",
      ...options,
    });
  }

  /**
   * Get Recording Wordcloud
   */
  public static getRecordingWordcloud<ThrowOnError extends boolean = false>(
    options: Options<GetRecordingWordcloudData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetRecordingWordcloudResponses, GetRecordingWordcloudErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/wordcloud.svg",
      ...options,
    });
  }

  /**
   * Reprocess Recording
   */
  public static reprocessRecording<ThrowOnError extends boolean = false>(
    options: Options<ReprocessRecordingData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ReprocessRecordingResponses, ReprocessRecordingErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/reprocess",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Revoke Shares
   */
  public static revokeShares<ThrowOnError extends boolean = false>(options: Options<RevokeSharesData, ThrowOnError>) {
    return (options.client ?? client).delete<RevokeSharesResponses, RevokeSharesErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/share",
      ...options,
    });
  }

  /**
   * Create Share
   * A read-only link to this one recording, for people without an account. Revoke with DELETE.
   */
  public static createShare<ThrowOnError extends boolean = false>(options: Options<CreateShareData, ThrowOnError>) {
    return (options.client ?? client).post<CreateShareResponses, CreateShareErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/share",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * List Shares
   */
  public static listShares<ThrowOnError extends boolean = false>(options: Options<ListSharesData, ThrowOnError>) {
    return (options.client ?? client).get<ListSharesResponses, ListSharesErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/shares",
      ...options,
    });
  }

  /**
   * Export Recording
   * The transcript as txt, md, srt, vtt or json (a download).
   */
  public static exportRecording<ThrowOnError extends boolean = false>(
    options: Options<ExportRecordingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ExportRecordingResponses, ExportRecordingErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/export.{fmt}",
      ...options,
    });
  }

  /**
   * Edit Segment
   * Correct a transcript line (text and/or speaker); the recording is re-analysed afterwards.
   */
  public static editSegment<ThrowOnError extends boolean = false>(options: Options<EditSegmentData, ThrowOnError>) {
    return (options.client ?? client).patch<EditSegmentResponses, EditSegmentErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/segments/{idx}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * List Segment Edits
   */
  public static listSegmentEdits<ThrowOnError extends boolean = false>(
    options: Options<ListSegmentEditsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListSegmentEditsResponses, ListSegmentEditsErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/edits",
      ...options,
    });
  }

  /**
   * List Outputs
   * Results of LLM pipeline steps for this recording.
   */
  public static listOutputs<ThrowOnError extends boolean = false>(options: Options<ListOutputsData, ThrowOnError>) {
    return (options.client ?? client).get<ListOutputsResponses, ListOutputsErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/outputs",
      ...options,
    });
  }
}

export class Imports {
  /**
   * Import Transcript
   * Import a transcript into a namespace (editors; admins may name a new namespace). Analysis is queued as a job.
   */
  public static importTranscript<ThrowOnError extends boolean = false>(
    options: Options<ImportTranscriptData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ImportTranscriptResponses, ImportTranscriptErrors, ThrowOnError>({
      url: "/api/v1/import",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Preview Import
   * Parse without saving: what the importer would make of this text or file.
   */
  public static previewImport<ThrowOnError extends boolean = false>(options: Options<PreviewImportData, ThrowOnError>) {
    return (options.client ?? client).post<PreviewImportResponses, PreviewImportErrors, ThrowOnError>({
      url: "/api/v1/import/preview",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Search {
  /**
   * Search Transcripts
   */
  public static searchTranscripts<ThrowOnError extends boolean = false>(
    options: Options<SearchTranscriptsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<SearchTranscriptsResponses, SearchTranscriptsErrors, ThrowOnError>({
      url: "/api/v1/search",
      ...options,
    });
  }

  /**
   * Get Graph
   * Speakers and entities as a graph, over the namespaces you can read (isolated ones only in their own scope).
   */
  public static getGraph<ThrowOnError extends boolean = false>(options?: Options<GetGraphData, ThrowOnError>) {
    return (options?.client ?? client).get<GetGraphResponses, GetGraphErrors, ThrowOnError>({
      url: "/api/v1/graph",
      ...options,
    });
  }

  /**
   * List Mentions
   */
  public static listMentions<ThrowOnError extends boolean = false>(options: Options<ListMentionsData, ThrowOnError>) {
    return (options.client ?? client).get<ListMentionsResponses, ListMentionsErrors, ThrowOnError>({
      url: "/api/v1/mentions",
      ...options,
    });
  }
}

export class Speakers {
  /**
   * List Speakers
   * A namespace's speakers, its recent merges (undoable) and links to speakers in other namespaces.
   */
  public static listSpeakers<ThrowOnError extends boolean = false>(options: Options<ListSpeakersData, ThrowOnError>) {
    return (options.client ?? client).get<ListSpeakersResponses, ListSpeakersErrors, ThrowOnError>({
      url: "/api/v1/speakers",
      ...options,
    });
  }

  /**
   * List Speaker Recordings
   */
  public static listSpeakerRecordings<ThrowOnError extends boolean = false>(
    options: Options<ListSpeakerRecordingsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListSpeakerRecordingsResponses, ListSpeakerRecordingsErrors, ThrowOnError>({
      url: "/api/v1/speakers/{sid}/recordings",
      ...options,
    });
  }

  /**
   * Rename Speaker
   */
  public static renameSpeaker<ThrowOnError extends boolean = false>(options: Options<RenameSpeakerData, ThrowOnError>) {
    return (options.client ?? client).post<RenameSpeakerResponses, RenameSpeakerErrors, ThrowOnError>({
      url: "/api/v1/speakers/{sid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Merge Speaker
   * Fold this speaker into ``into`` (same namespace). Undo with POST /merges/{merge_id}/undo.
   */
  public static mergeSpeaker<ThrowOnError extends boolean = false>(options: Options<MergeSpeakerData, ThrowOnError>) {
    return (options.client ?? client).post<MergeSpeakerResponses, MergeSpeakerErrors, ThrowOnError>({
      url: "/api/v1/speakers/{sid}/merge",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Undo Speaker Merge
   */
  public static undoSpeakerMerge<ThrowOnError extends boolean = false>(
    options: Options<UndoSpeakerMergeData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<UndoSpeakerMergeResponses, UndoSpeakerMergeErrors, ThrowOnError>({
      url: "/api/v1/merges/{mid}/undo",
      ...options,
    });
  }

  /**
   * Link Speaker
   * Mark this speaker and one in another namespace as the same person (you need editor access to both).
   */
  public static linkSpeaker<ThrowOnError extends boolean = false>(options: Options<LinkSpeakerData, ThrowOnError>) {
    return (options.client ?? client).post<LinkSpeakerResponses, LinkSpeakerErrors, ThrowOnError>({
      url: "/api/v1/speakers/{sid}/link",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Entities {
  /**
   * List Entities
   * Entities in the namespaces you can read. `types` and `namespaces` are comma-separated; `group` joins same-named ones.
   */
  public static listEntities<ThrowOnError extends boolean = false>(options?: Options<ListEntitiesData, ThrowOnError>) {
    return (options?.client ?? client).get<ListEntitiesResponses, ListEntitiesErrors, ThrowOnError>({
      url: "/api/v1/entities",
      ...options,
    });
  }

  /**
   * List Entity Types
   */
  public static listEntityTypes<ThrowOnError extends boolean = false>(
    options?: Options<ListEntityTypesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListEntityTypesResponses, unknown, ThrowOnError>({
      url: "/api/v1/entities/types",
      ...options,
    });
  }

  /**
   * List Entity Suggestions
   * Entities that are probably the same thing (same letters, acronyms, sound-alikes), to merge or mark as different.
   */
  public static listEntitySuggestions<ThrowOnError extends boolean = false>(
    options?: Options<ListEntitySuggestionsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListEntitySuggestionsResponses, ListEntitySuggestionsErrors, ThrowOnError>({
      url: "/api/v1/entities/suggestions",
      ...options,
    });
  }

  /**
   * List Entity Merges
   */
  public static listEntityMerges<ThrowOnError extends boolean = false>(
    options?: Options<ListEntityMergesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListEntityMergesResponses, unknown, ThrowOnError>({
      url: "/api/v1/entities/merges",
      ...options,
    });
  }

  /**
   * Get Entity Timeline
   * Mentions per month (or week) per namespace for comma-separated entity ids.
   */
  public static getEntityTimeline<ThrowOnError extends boolean = false>(
    options: Options<GetEntityTimelineData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetEntityTimelineResponses, GetEntityTimelineErrors, ThrowOnError>({
      url: "/api/v1/entities/timeline",
      ...options,
    });
  }

  /**
   * Retype Entities
   */
  public static retypeEntities<ThrowOnError extends boolean = false>(
    options: Options<RetypeEntitiesData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<RetypeEntitiesResponses, RetypeEntitiesErrors, ThrowOnError>({
      url: "/api/v1/entities/retype",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Merge Entities
   */
  public static mergeEntities<ThrowOnError extends boolean = false>(options: Options<MergeEntitiesData, ThrowOnError>) {
    return (options.client ?? client).post<MergeEntitiesResponses, MergeEntitiesErrors, ThrowOnError>({
      url: "/api/v1/entities/merge",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Undo Entity Merge
   */
  public static undoEntityMerge<ThrowOnError extends boolean = false>(
    options: Options<UndoEntityMergeData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<UndoEntityMergeResponses, UndoEntityMergeErrors, ThrowOnError>({
      url: "/api/v1/entities/merges/{mid}/undo",
      ...options,
    });
  }

  /**
   * Mark Entities Not Same
   * Stop suggesting that these two are the same.
   */
  public static markEntitiesNotSame<ThrowOnError extends boolean = false>(
    options: Options<MarkEntitiesNotSameData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<MarkEntitiesNotSameResponses, MarkEntitiesNotSameErrors, ThrowOnError>({
      url: "/api/v1/entities/not-same",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Entity
   */
  public static getEntity<ThrowOnError extends boolean = false>(options: Options<GetEntityData, ThrowOnError>) {
    return (options.client ?? client).get<GetEntityResponses, GetEntityErrors, ThrowOnError>({
      url: "/api/v1/entities/{eid}",
      ...options,
    });
  }

  /**
   * List Entity Mentions
   * Every line that mentions the entity; `highlight` is the [start, end) of the mention in `text`. sort: newest, oldest, most.
   */
  public static listEntityMentions<ThrowOnError extends boolean = false>(
    options: Options<ListEntityMentionsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ListEntityMentionsResponses, ListEntityMentionsErrors, ThrowOnError>({
      url: "/api/v1/entities/{eid}/mentions",
      ...options,
    });
  }

  /**
   * Get Entity Connections
   * Entities mentioned together with this one, and who mentions it most.
   */
  public static getEntityConnections<ThrowOnError extends boolean = false>(
    options: Options<GetEntityConnectionsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetEntityConnectionsResponses, GetEntityConnectionsErrors, ThrowOnError>({
      url: "/api/v1/entities/{eid}/connections",
      ...options,
    });
  }

  /**
   * Rename Entity
   * Rename; with `correct`, also fix the transcript lines (re-analysing the recordings). `dry_run` previews the lines.
   */
  public static renameEntity<ThrowOnError extends boolean = false>(options: Options<RenameEntityData, ThrowOnError>) {
    return (options.client ?? client).post<RenameEntityResponses, RenameEntityErrors, ThrowOnError>({
      url: "/api/v1/entities/{eid}/rename",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Hide Entity
   */
  public static hideEntity<ThrowOnError extends boolean = false>(options: Options<HideEntityData, ThrowOnError>) {
    return (options.client ?? client).post<HideEntityResponses, HideEntityErrors, ThrowOnError>({
      url: "/api/v1/entities/{eid}/hide",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Link Entity
   * Say an entity in another namespace is the same thing (they stay separate; the graph joins them).
   */
  public static linkEntity<ThrowOnError extends boolean = false>(options: Options<LinkEntityData, ThrowOnError>) {
    return (options.client ?? client).post<LinkEntityResponses, LinkEntityErrors, ThrowOnError>({
      url: "/api/v1/entities/{eid}/link",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Unlink Entity
   */
  public static unlinkEntity<ThrowOnError extends boolean = false>(options: Options<UnlinkEntityData, ThrowOnError>) {
    return (options.client ?? client).delete<UnlinkEntityResponses, UnlinkEntityErrors, ThrowOnError>({
      url: "/api/v1/entities/{eid}/link/{other}",
      ...options,
    });
  }

  /**
   * Move Mention
   * Point one mention at another entity (or a new one), or say it isn't an entity. Survives re-analysis.
   */
  public static moveMention<ThrowOnError extends boolean = false>(options: Options<MoveMentionData, ThrowOnError>) {
    return (options.client ?? client).post<MoveMentionResponses, MoveMentionErrors, ThrowOnError>({
      url: "/api/v1/mentions/{mention}/move",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Explore Graph
   * The neighbourhood of a node (`e<id>` for an entity, a speaker node id...). scope: `all` (shared graphs) or `ns:<name>`.
   */
  public static exploreGraph<ThrowOnError extends boolean = false>(options: Options<ExploreGraphData, ThrowOnError>) {
    return (options.client ?? client).get<ExploreGraphResponses, ExploreGraphErrors, ThrowOnError>({
      url: "/api/v1/graph/explore",
      ...options,
    });
  }

  /**
   * Find Graph Path
   * The shortest chain of links between two nodes, with the lines that show each link.
   */
  public static findGraphPath<ThrowOnError extends boolean = false>(options: Options<FindGraphPathData, ThrowOnError>) {
    return (options.client ?? client).get<FindGraphPathResponses, FindGraphPathErrors, ThrowOnError>({
      url: "/api/v1/graph/path",
      ...options,
    });
  }
}

export class Metadata {
  /**
   * Get Recording Metadata
   */
  public static getRecordingMetadata<ThrowOnError extends boolean = false>(
    options: Options<GetRecordingMetadataData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetRecordingMetadataResponses, GetRecordingMetadataErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/metadata",
      ...options,
    });
  }

  /**
   * Update Recording Metadata
   * Save fields (null clears one) or put them back to their derived values. The access fields need an owner.
   */
  public static updateRecordingMetadata<ThrowOnError extends boolean = false>(
    options: Options<UpdateRecordingMetadataData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      UpdateRecordingMetadataResponses,
      UpdateRecordingMetadataErrors,
      ThrowOnError
    >({
      url: "/api/v1/recordings/{rid}/metadata",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * List Recording Metadata History
   */
  public static listRecordingMetadataHistory<ThrowOnError extends boolean = false>(
    options: Options<ListRecordingMetadataHistoryData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      ListRecordingMetadataHistoryResponses,
      ListRecordingMetadataHistoryErrors,
      ThrowOnError
    >({
      url: "/api/v1/recordings/{rid}/metadata/history",
      ...options,
    });
  }

  /**
   * Revert Metadata Edit
   * Put a recording's (editors) or namespace's (owners) metadata back to how it was before this edit.
   */
  public static revertMetadataEdit<ThrowOnError extends boolean = false>(
    options: Options<RevertMetadataEditData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<RevertMetadataEditResponses, RevertMetadataEditErrors, ThrowOnError>({
      url: "/api/v1/metadata/edits/{eid}/revert",
      ...options,
    });
  }

  /**
   * Get Namespace Metadata
   */
  public static getNamespaceMetadata<ThrowOnError extends boolean = false>(
    options: Options<GetNamespaceMetadataData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetNamespaceMetadataResponses, GetNamespaceMetadataErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/metadata",
      ...options,
    });
  }

  /**
   * Update Namespace Metadata
   * Collection metadata and the profile (required fields, defaults, vocabularies, default access). Owners only.
   */
  public static updateNamespaceMetadata<ThrowOnError extends boolean = false>(
    options: Options<UpdateNamespaceMetadataData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      UpdateNamespaceMetadataResponses,
      UpdateNamespaceMetadataErrors,
      ThrowOnError
    >({
      url: "/api/v1/namespaces/{name}/metadata",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Bulk Update Metadata
   * Set or clear fields on many recordings. `dry_run` (the default) reports what would change.
   */
  public static bulkUpdateMetadata<ThrowOnError extends boolean = false>(
    options: Options<BulkUpdateMetadataData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<BulkUpdateMetadataResponses, BulkUpdateMetadataErrors, ThrowOnError>({
      url: "/api/v1/metadata/bulk",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Video {
  /**
   * Get Media
   * The video (or audio) file, with byte ranges. Accepts a bearer token, a share link (``?s=``) or a signed link.
   */
  public static getMedia<ThrowOnError extends boolean = false>(options: Options<GetMediaData, ThrowOnError>) {
    return (options.client ?? client).get<GetMediaResponses, GetMediaErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/media",
      ...options,
    });
  }

  /**
   * Get Frame
   * A still (shot frame, text-on-screen frame or face crop).
   */
  public static getFrame<ThrowOnError extends boolean = false>(options: Options<GetFrameData, ThrowOnError>) {
    return (options.client ?? client).get<GetFrameResponses, GetFrameErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/frames/{name}",
      ...options,
    });
  }

  /**
   * Fix Screen Text
   * Correct text read off the screen (the machine's reading is kept as `machine_text`).
   */
  public static fixScreenText<ThrowOnError extends boolean = false>(options: Options<FixScreenTextData, ThrowOnError>) {
    return (options.client ?? client).patch<FixScreenTextResponses, FixScreenTextErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/ocr/{span}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Face Track
   * Not a face: remove this track (and its crop) from the recording.
   */
  public static deleteFaceTrack<ThrowOnError extends boolean = false>(
    options: Options<DeleteFaceTrackData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteFaceTrackResponses, DeleteFaceTrackErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/faces/{track}",
      ...options,
    });
  }

  /**
   * Delete Namespace Faces
   * Delete every face, track and crop in the namespace. Owners only.
   */
  public static deleteNamespaceFaces<ThrowOnError extends boolean = false>(
    options: Options<DeleteNamespaceFacesData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteNamespaceFacesResponses, DeleteNamespaceFacesErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/faces",
      ...options,
    });
  }

  /**
   * Get Namespace Faces
   * The face mode (with who set it and why), the faces found (with suggested names) and recent merges.
   *
   * Each face's `cover_url` is a signed link to its crop.
   */
  public static getNamespaceFaces<ThrowOnError extends boolean = false>(
    options: Options<GetNamespaceFacesData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetNamespaceFacesResponses, GetNamespaceFacesErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/faces",
      ...options,
    });
  }

  /**
   * Set Namespace Faces Mode
   * off, detect or recognize (which needs a purpose). Owners only. `reprocess` queues the namespace's videos.
   */
  public static setNamespaceFacesMode<ThrowOnError extends boolean = false>(
    options: Options<SetNamespaceFacesModeData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<SetNamespaceFacesModeResponses, SetNamespaceFacesModeErrors, ThrowOnError>({
      url: "/api/v1/namespaces/{name}/faces/mode",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Undo Face Merge
   */
  public static undoFaceMerge<ThrowOnError extends boolean = false>(options: Options<UndoFaceMergeData, ThrowOnError>) {
    return (options.client ?? client).post<UndoFaceMergeResponses, UndoFaceMergeErrors, ThrowOnError>({
      url: "/api/v1/faces/merges/{mid}/undo",
      ...options,
    });
  }

  /**
   * Delete Face
   * Delete a face with its tracks and crops. Owners only.
   */
  public static deleteFace<ThrowOnError extends boolean = false>(options: Options<DeleteFaceData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteFaceResponses, DeleteFaceErrors, ThrowOnError>({
      url: "/api/v1/faces/{fid}",
      ...options,
    });
  }

  /**
   * Rename Face
   */
  public static renameFace<ThrowOnError extends boolean = false>(options: Options<RenameFaceData, ThrowOnError>) {
    return (options.client ?? client).post<RenameFaceResponses, RenameFaceErrors, ThrowOnError>({
      url: "/api/v1/faces/{fid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Merge Face
   * Merge this face into another (the same person).
   */
  public static mergeFace<ThrowOnError extends boolean = false>(options: Options<MergeFaceData, ThrowOnError>) {
    return (options.client ?? client).post<MergeFaceResponses, MergeFaceErrors, ThrowOnError>({
      url: "/api/v1/faces/{fid}/merge",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Link Face Speaker
   * Say whose voice goes with this face (null unlinks).
   */
  public static linkFaceSpeaker<ThrowOnError extends boolean = false>(
    options: Options<LinkFaceSpeakerData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<LinkFaceSpeakerResponses, LinkFaceSpeakerErrors, ThrowOnError>({
      url: "/api/v1/faces/{fid}/speaker",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Dismiss Face Suggestion
   * Drop a suggestion (`kind` face or speaker, with its id).
   */
  public static dismissFaceSuggestion<ThrowOnError extends boolean = false>(
    options: Options<DismissFaceSuggestionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<DismissFaceSuggestionResponses, DismissFaceSuggestionErrors, ThrowOnError>({
      url: "/api/v1/faces/{fid}/dismiss",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Iiif {
  /**
   * Get Recording Iiif
   * The recording's manifest (as `json`), whether it is published, its layers, a schema check and viewer links.
   */
  public static getRecordingIiif<ThrowOnError extends boolean = false>(
    options: Options<GetRecordingIiifData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetRecordingIiifResponses, GetRecordingIiifErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/iiif",
      ...options,
    });
  }

  /**
   * Get Content State
   * A IIIF Content State pointing at a moment (t0..t1 seconds) of the recording, and links that open it.
   */
  public static getContentState<ThrowOnError extends boolean = false>(
    options: Options<GetContentStateData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetContentStateResponses, GetContentStateErrors, ThrowOnError>({
      url: "/api/v1/recordings/{rid}/content-state",
      ...options,
    });
  }

  /**
   * Preview Iiif Import
   * What a IIIF manifest or collection would import (Presentation 3; version 2 is refused with a message).
   */
  public static previewIiifImport<ThrowOnError extends boolean = false>(
    options: Options<PreviewIiifImportData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<PreviewIiifImportResponses, PreviewIiifImportErrors, ThrowOnError>({
      url: "/api/v1/import/iiif/preview",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Import Iiif
   * Import recordings (audio, captions and metadata) from a IIIF manifest or collection into a namespace.
   *
   * With `wait`, answers with the new recording ids; otherwise imports in the background (202).
   */
  public static importIiif<ThrowOnError extends boolean = false>(options: Options<ImportIiifData, ThrowOnError>) {
    return (options.client ?? client).post<ImportIiifResponses, ImportIiifErrors, ThrowOnError>({
      url: "/api/v1/import/iiif",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Jobs {
  /**
   * List Jobs
   * Recent jobs with counts by status, plus the latest job's step and log (for the progress bar).
   */
  public static listJobs<ThrowOnError extends boolean = false>(options?: Options<ListJobsData, ThrowOnError>) {
    return (options?.client ?? client).get<ListJobsResponses, ListJobsErrors, ThrowOnError>({
      url: "/api/v1/jobs",
      ...options,
    });
  }

  /**
   * Create Jobs
   * Queue recordings (these steps, a pipeline, or their namespace's pipeline) and/or everything pending in a namespace.
   */
  public static createJobs<ThrowOnError extends boolean = false>(options: Options<CreateJobsData, ThrowOnError>) {
    return (options.client ?? client).post<CreateJobsResponses, CreateJobsErrors, ThrowOnError>({
      url: "/api/v1/jobs",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Job
   */
  public static getJob<ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>) {
    return (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({
      url: "/api/v1/jobs/{jid}",
      ...options,
    });
  }

  /**
   * Queue Step
   * The web app's batch buttons: queue one step for everything that needs it (``transcribe``, ``diarize``,
   * ``analyze``, ``summarize``, ``report``), or (admins) ``run``/``scan`` the configured folders.
   */
  public static queueStep<ThrowOnError extends boolean = false>(options: Options<QueueStepData, ThrowOnError>) {
    return (options.client ?? client).post<QueueStepResponses, QueueStepErrors, ThrowOnError>({
      url: "/api/v1/jobs/steps/{step}",
      ...options,
    });
  }

  /**
   * Cancel Job
   */
  public static cancelJob<ThrowOnError extends boolean = false>(options: Options<CancelJobData, ThrowOnError>) {
    return (options.client ?? client).post<CancelJobResponses, CancelJobErrors, ThrowOnError>({
      url: "/api/v1/jobs/{jid}/cancel",
      ...options,
    });
  }

  /**
   * Retry Job
   */
  public static retryJob<ThrowOnError extends boolean = false>(options: Options<RetryJobData, ThrowOnError>) {
    return (options.client ?? client).post<RetryJobResponses, RetryJobErrors, ThrowOnError>({
      url: "/api/v1/jobs/{jid}/retry",
      ...options,
    });
  }

  /**
   * List Workers
   */
  public static listWorkers<ThrowOnError extends boolean = false>(options?: Options<ListWorkersData, ThrowOnError>) {
    return (options?.client ?? client).get<ListWorkersResponses, unknown, ThrowOnError>({
      url: "/api/v1/workers",
      ...options,
    });
  }

  /**
   * Stream Events
   * Server-sent events: one ``job`` event per job change in namespaces you can read, from ``since`` (default: now).
   * ``once=true`` sends what has changed and closes. Read it with fetch (it needs the Authorization header).
   */
  public static streamEvents<ThrowOnError extends boolean = false>(options?: Options<StreamEventsData, ThrowOnError>) {
    return (options?.client ?? client).sse.get<StreamEventsResponses, StreamEventsErrors, ThrowOnError>({
      url: "/api/v1/events",
      ...options,
    });
  }
}

export class Sources {
  /**
   * List Backends
   * The kinds of storage a source can be, with their settings and secrets.
   */
  public static listBackends<ThrowOnError extends boolean = false>(options?: Options<ListBackendsData, ThrowOnError>) {
    return (options?.client ?? client).get<ListBackendsResponses, unknown, ThrowOnError>({
      url: "/api/v1/sources/backends",
      ...options,
    });
  }

  /**
   * List Sources
   */
  public static listSources<ThrowOnError extends boolean = false>(options?: Options<ListSourcesData, ThrowOnError>) {
    return (options?.client ?? client).get<ListSourcesResponses, unknown, ThrowOnError>({
      url: "/api/v1/sources",
      ...options,
    });
  }

  /**
   * Create Source
   * Add a source and test it; secrets are stored encrypted and never shown again.
   */
  public static createSource<ThrowOnError extends boolean = false>(options: Options<CreateSourceData, ThrowOnError>) {
    return (options.client ?? client).post<CreateSourceResponses, CreateSourceErrors, ThrowOnError>({
      url: "/api/v1/sources",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Source
   * Remove a source and its watched folders.
   */
  public static deleteSource<ThrowOnError extends boolean = false>(options: Options<DeleteSourceData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteSourceResponses, DeleteSourceErrors, ThrowOnError>({
      url: "/api/v1/sources/{sid}",
      ...options,
    });
  }

  /**
   * Update Source
   */
  public static updateSource<ThrowOnError extends boolean = false>(options: Options<UpdateSourceData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdateSourceResponses, UpdateSourceErrors, ThrowOnError>({
      url: "/api/v1/sources/{sid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Test Source
   */
  public static testSource<ThrowOnError extends boolean = false>(options: Options<TestSourceData, ThrowOnError>) {
    return (options.client ?? client).post<TestSourceResponses, TestSourceErrors, ThrowOnError>({
      url: "/api/v1/sources/{sid}/test",
      ...options,
    });
  }

  /**
   * Browse Source
   * The folders and files at one path of a source (for local sources, no path lists the allowed roots).
   */
  public static browseSource<ThrowOnError extends boolean = false>(options: Options<BrowseSourceData, ThrowOnError>) {
    return (options.client ?? client).get<BrowseSourceResponses, BrowseSourceErrors, ThrowOnError>({
      url: "/api/v1/sources/{sid}/browse",
      ...options,
    });
  }

  /**
   * List Watches
   * Watched folders: all of them for admins, else those feeding namespaces you own.
   */
  public static listWatches<ThrowOnError extends boolean = false>(options?: Options<ListWatchesData, ThrowOnError>) {
    return (options?.client ?? client).get<ListWatchesResponses, unknown, ThrowOnError>({
      url: "/api/v1/watches",
      ...options,
    });
  }

  /**
   * Create Watch
   * Watch a folder of a source; new files there are imported into the namespace (which is created if needed).
   */
  public static createWatch<ThrowOnError extends boolean = false>(options: Options<CreateWatchData, ThrowOnError>) {
    return (options.client ?? client).post<CreateWatchResponses, CreateWatchErrors, ThrowOnError>({
      url: "/api/v1/watches",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Preview Watch
   * How many files a watched folder would pick up (the backfill count), before creating it.
   */
  public static previewWatch<ThrowOnError extends boolean = false>(options: Options<PreviewWatchData, ThrowOnError>) {
    return (options.client ?? client).post<PreviewWatchResponses, PreviewWatchErrors, ThrowOnError>({
      url: "/api/v1/watches/preview",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Watch
   */
  public static deleteWatch<ThrowOnError extends boolean = false>(options: Options<DeleteWatchData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteWatchResponses, DeleteWatchErrors, ThrowOnError>({
      url: "/api/v1/watches/{wid}",
      ...options,
    });
  }

  /**
   * Update Watch
   */
  public static updateWatch<ThrowOnError extends boolean = false>(options: Options<UpdateWatchData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdateWatchResponses, UpdateWatchErrors, ThrowOnError>({
      url: "/api/v1/watches/{wid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Scan Watch
   * Look for new files now instead of waiting for the next poll.
   */
  public static scanWatch<ThrowOnError extends boolean = false>(options: Options<ScanWatchData, ThrowOnError>) {
    return (options.client ?? client).post<ScanWatchResponses, ScanWatchErrors, ThrowOnError>({
      url: "/api/v1/watches/{wid}/scan",
      ...options,
    });
  }
}

export class Templates {
  /**
   * List Templates
   */
  public static listTemplates<ThrowOnError extends boolean = false>(
    options?: Options<ListTemplatesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListTemplatesResponses, unknown, ThrowOnError>({
      url: "/api/v1/templates",
      ...options,
    });
  }

  /**
   * Create Template
   */
  public static createTemplate<ThrowOnError extends boolean = false>(
    options: Options<CreateTemplateData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateTemplateResponses, CreateTemplateErrors, ThrowOnError>({
      url: "/api/v1/templates",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Preview Template
   * Render a template (saved, or the unsaved text in the editor) against a recording; run=true also calls the model.
   *
   * A template that fails to render answers ok=false with the error, so the editor can show it inline.
   */
  public static previewTemplate<ThrowOnError extends boolean = false>(
    options: Options<PreviewTemplateData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<PreviewTemplateResponses, PreviewTemplateErrors, ThrowOnError>({
      url: "/api/v1/templates/preview",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Template
   * One version (default: the current one) and the list of versions.
   */
  public static getTemplate<ThrowOnError extends boolean = false>(options: Options<GetTemplateData, ThrowOnError>) {
    return (options.client ?? client).get<GetTemplateResponses, GetTemplateErrors, ThrowOnError>({
      url: "/api/v1/templates/{tid}",
      ...options,
    });
  }

  /**
   * Create Template Version
   */
  public static createTemplateVersion<ThrowOnError extends boolean = false>(
    options: Options<CreateTemplateVersionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateTemplateVersionResponses, CreateTemplateVersionErrors, ThrowOnError>({
      url: "/api/v1/templates/{tid}/versions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Diff Template Versions
   * A unified diff between two versions.
   */
  public static diffTemplateVersions<ThrowOnError extends boolean = false>(
    options: Options<DiffTemplateVersionsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<DiffTemplateVersionsResponses, DiffTemplateVersionsErrors, ThrowOnError>({
      url: "/api/v1/templates/{tid}/diff",
      ...options,
    });
  }
}

export class Pipelines {
  /**
   * List Pipelines
   * Saved pipelines, plus what a pipeline can be built from.
   */
  public static listPipelines<ThrowOnError extends boolean = false>(
    options?: Options<ListPipelinesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListPipelinesResponses, unknown, ThrowOnError>({
      url: "/api/v1/pipelines",
      ...options,
    });
  }

  /**
   * Create Pipeline
   */
  public static createPipeline<ThrowOnError extends boolean = false>(
    options: Options<CreatePipelineData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreatePipelineResponses, CreatePipelineErrors, ThrowOnError>({
      url: "/api/v1/pipelines",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Pipeline
   * One version (default: the current one) and the list of versions.
   */
  public static getPipeline<ThrowOnError extends boolean = false>(options: Options<GetPipelineData, ThrowOnError>) {
    return (options.client ?? client).get<GetPipelineResponses, GetPipelineErrors, ThrowOnError>({
      url: "/api/v1/pipelines/{pid}",
      ...options,
    });
  }

  /**
   * Create Pipeline Version
   */
  public static createPipelineVersion<ThrowOnError extends boolean = false>(
    options: Options<CreatePipelineVersionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreatePipelineVersionResponses, CreatePipelineVersionErrors, ThrowOnError>({
      url: "/api/v1/pipelines/{pid}/versions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Run Pipeline
   * Run this pipeline on one recording now (its outputs are kept).
   */
  public static runPipeline<ThrowOnError extends boolean = false>(options: Options<RunPipelineData, ThrowOnError>) {
    return (options.client ?? client).post<RunPipelineResponses, RunPipelineErrors, ThrowOnError>({
      url: "/api/v1/pipelines/{pid}/run",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Chats {
  /**
   * List Chats
   * Your conversations, most recent first.
   */
  public static listChats<ThrowOnError extends boolean = false>(options?: Options<ListChatsData, ThrowOnError>) {
    return (options?.client ?? client).get<ListChatsResponses, unknown, ThrowOnError>({
      url: "/api/v1/chats",
      ...options,
    });
  }

  /**
   * Create Chat
   */
  public static createChat<ThrowOnError extends boolean = false>(options?: Options<CreateChatData, ThrowOnError>) {
    return (options?.client ?? client).post<CreateChatResponses, CreateChatErrors, ThrowOnError>({
      url: "/api/v1/chats",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete Chat
   */
  public static deleteChat<ThrowOnError extends boolean = false>(options: Options<DeleteChatData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteChatResponses, DeleteChatErrors, ThrowOnError>({
      url: "/api/v1/chats/{cid}",
      ...options,
    });
  }

  /**
   * Get Chat
   * A conversation with its messages. Citations follow your current access: ones you can no longer read are left out.
   */
  public static getChat<ThrowOnError extends boolean = false>(options: Options<GetChatData, ThrowOnError>) {
    return (options.client ?? client).get<GetChatResponses, GetChatErrors, ThrowOnError>({
      url: "/api/v1/chats/{cid}",
      ...options,
    });
  }

  /**
   * Update Chat
   * Rename a conversation or change what it draws on.
   */
  public static updateChat<ThrowOnError extends boolean = false>(options: Options<UpdateChatData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdateChatResponses, UpdateChatErrors, ThrowOnError>({
      url: "/api/v1/chats/{cid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Send Message
   * Ask a question. Streams events: step, approval, notice, passages, token (answer text), error, done (the saved message id).
   */
  public static sendMessage<ThrowOnError extends boolean = false>(options: Options<SendMessageData, ThrowOnError>) {
    return (options.client ?? client).sse.post<SendMessageResponses, SendMessageErrors, ThrowOnError>({
      url: "/api/v1/chats/{cid}/messages",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Check Message
   * Re-check each cited claim of an answer against the excerpts it cites; the verdict is saved on the message.
   */
  public static checkMessage<ThrowOnError extends boolean = false>(options: Options<CheckMessageData, ThrowOnError>) {
    return (options.client ?? client).post<CheckMessageResponses, CheckMessageErrors, ThrowOnError>({
      url: "/api/v1/chats/{cid}/messages/{mid}/check",
      ...options,
    });
  }

  /**
   * List Approvals
   * Work the assistant proposed for you to approve (and what became of it), newest first.
   */
  public static listApprovals<ThrowOnError extends boolean = false>(
    options?: Options<ListApprovalsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListApprovalsResponses, ListApprovalsErrors, ThrowOnError>({
      url: "/api/v1/approvals",
      ...options,
    });
  }

  /**
   * Decide Approval
   * Approve (or run a sample of, or decline) something the assistant proposed. Each approval is decided once.
   */
  public static decideApproval<ThrowOnError extends boolean = false>(
    options: Options<DecideApprovalData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<DecideApprovalResponses, DecideApprovalErrors, ThrowOnError>({
      url: "/api/v1/approvals/{aid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Collections {
  /**
   * List Collections
   */
  public static listCollections<ThrowOnError extends boolean = false>(
    options?: Options<ListCollectionsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListCollectionsResponses, unknown, ThrowOnError>({
      url: "/api/v1/collections",
      ...options,
    });
  }

  /**
   * Create Collection
   */
  public static createCollection<ThrowOnError extends boolean = false>(
    options: Options<CreateCollectionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateCollectionResponses, CreateCollectionErrors, ThrowOnError>({
      url: "/api/v1/collections",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Collection
   */
  public static deleteCollection<ThrowOnError extends boolean = false>(
    options: Options<DeleteCollectionData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteCollectionResponses, DeleteCollectionErrors, ThrowOnError>({
      url: "/api/v1/collections/{cid}",
      ...options,
    });
  }

  /**
   * Get Collection
   * The collection with how many recordings you can read in it, and the newest 200 of them.
   */
  public static getCollection<ThrowOnError extends boolean = false>(options: Options<GetCollectionData, ThrowOnError>) {
    return (options.client ?? client).get<GetCollectionResponses, GetCollectionErrors, ThrowOnError>({
      url: "/api/v1/collections/{cid}",
      ...options,
    });
  }

  /**
   * Update Collection
   * Change your collection. A filter collection takes a new filter; a fixed one a new list of recordings.
   */
  public static updateCollection<ThrowOnError extends boolean = false>(
    options: Options<UpdateCollectionData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<UpdateCollectionResponses, UpdateCollectionErrors, ThrowOnError>({
      url: "/api/v1/collections/{cid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Batches {
  /**
   * Estimate Batch
   * What a run would cost, before starting it. Only recordings you can change count; the rest are `skipped`.
   */
  public static estimateBatch<ThrowOnError extends boolean = false>(options: Options<EstimateBatchData, ThrowOnError>) {
    return (options.client ?? client).post<EstimateBatchResponses, EstimateBatchErrors, ThrowOnError>({
      url: "/api/v1/batches/estimate",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * List Batches
   * Your batch runs (everyone's, for admins), newest first.
   */
  public static listBatches<ThrowOnError extends boolean = false>(options?: Options<ListBatchesData, ThrowOnError>) {
    return (options?.client ?? client).get<ListBatchesResponses, unknown, ThrowOnError>({
      url: "/api/v1/batches",
      ...options,
    });
  }

  /**
   * Create Batch
   */
  public static createBatch<ThrowOnError extends boolean = false>(options: Options<CreateBatchData, ThrowOnError>) {
    return (options.client ?? client).post<CreateBatchResponses, CreateBatchErrors, ThrowOnError>({
      url: "/api/v1/batches",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Batch
   */
  public static getBatch<ThrowOnError extends boolean = false>(options: Options<GetBatchData, ThrowOnError>) {
    return (options.client ?? client).get<GetBatchResponses, GetBatchErrors, ThrowOnError>({
      url: "/api/v1/batches/{bid}",
      ...options,
    });
  }

  /**
   * Combine Batch
   * One overview written by the model from every recording's result, citing each as [n]; saved on the batch.
   */
  public static combineBatch<ThrowOnError extends boolean = false>(options: Options<CombineBatchData, ThrowOnError>) {
    return (options.client ?? client).post<CombineBatchResponses, CombineBatchErrors, ThrowOnError>({
      url: "/api/v1/batches/{bid}/combine",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Control Batch
   * continue (after a sample), pause, resume, cancel, or retry the failed recordings.
   */
  public static controlBatch<ThrowOnError extends boolean = false>(options: Options<ControlBatchData, ThrowOnError>) {
    return (options.client ?? client).post<ControlBatchResponses, ControlBatchErrors, ThrowOnError>({
      url: "/api/v1/batches/{bid}/{action}",
      ...options,
    });
  }

  /**
   * Get Batch Results
   * The run's outputs as one table: list-valued fields become one row per item (e.g. every action item).
   */
  public static getBatchResults<ThrowOnError extends boolean = false>(
    options: Options<GetBatchResultsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetBatchResultsResponses, GetBatchResultsErrors, ThrowOnError>({
      url: "/api/v1/batches/{bid}/results",
      ...options,
    });
  }

  /**
   * Export Batch Results
   */
  public static exportBatchResults<ThrowOnError extends boolean = false>(
    options: Options<ExportBatchResultsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<ExportBatchResultsResponses, ExportBatchResultsErrors, ThrowOnError>({
      url: "/api/v1/batches/{bid}/results.{fmt}",
      ...options,
    });
  }
}

export class Public {
  /**
   * Get Public Home
   * The home page: featured public recordings, for everyone, and the collections this visitor sees anything in.
   */
  public static getPublicHome<ThrowOnError extends boolean = false>(
    options?: Options<GetPublicHomeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetPublicHomeResponses, unknown, ThrowOnError>({
      url: "/api/v1/public/home",
      ...options,
    });
  }

  /**
   * Get Public Collection
   * A collection's page: its description and the recordings this visitor sees, newest first. Visitors see the public
   * ones; signed-in people also see restricted ones, locked; members see all of them. A collection with nothing for
   * this visitor answers 404, as a missing one does.
   */
  public static getPublicCollection<ThrowOnError extends boolean = false>(
    options: Options<GetPublicCollectionData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetPublicCollectionResponses, GetPublicCollectionErrors, ThrowOnError>({
      url: "/api/v1/public/collections/{name}",
      ...options,
    });
  }

  /**
   * Search Public
   * Search what this visitor may see: titles of the recordings they see listed, and the lines of the transcripts
   * they may read. Title matches come first. Restricted recordings (for signed-in people) and public ones with the
   * transcript closed match on their title only.
   */
  public static searchPublic<ThrowOnError extends boolean = false>(options?: Options<SearchPublicData, ThrowOnError>) {
    return (options?.client ?? client).get<SearchPublicResponses, SearchPublicErrors, ThrowOnError>({
      url: "/api/v1/public/search",
      ...options,
    });
  }

  /**
   * Get Public Recording
   * A recording's public page: what this visitor may see of it, and nothing more.
   *
   * Anyone sees a public recording's page, description and open parts; a signed-in person sees a restricted one's title
   * with a lock; people with a role in its namespace, given permission on the recording, or on the network of an IP
   * group that opens it, see all of it. Everything else answers 404, as a recording that doesn't exist would.
   */
  public static getPublicRecording<ThrowOnError extends boolean = false>(
    options: Options<GetPublicRecordingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetPublicRecordingResponses, GetPublicRecordingErrors, ThrowOnError>({
      url: "/api/v1/public/recordings/{rid}",
      ...options,
    });
  }

  /**
   * Request Access
   * Ask for access to a recording (signed in, without permission): its closed parts, or a restricted one. Asking
   * again replaces the earlier request. The namespace's owners hear of it by email when mail is set up; they approve
   * (which gives permission) or decline in the recording's access settings.
   */
  public static requestAccess<ThrowOnError extends boolean = false>(options: Options<RequestAccessData, ThrowOnError>) {
    return (options.client ?? client).post<RequestAccessResponses, RequestAccessErrors, ThrowOnError>({
      url: "/api/v1/public/recordings/{rid}/request",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class AccessRequests {
  /**
   * List Pending Access Requests
   * Requests waiting for an answer, for recordings in the namespaces you own (all of them for admins), newest
   * first. Each is answered in its recording's access settings.
   */
  public static listPendingAccessRequests<ThrowOnError extends boolean = false>(
    options?: Options<ListPendingAccessRequestsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<ListPendingAccessRequestsResponses, unknown, ThrowOnError>({
      url: "/api/v1/access-requests",
      ...options,
    });
  }
}
