// This file is auto-generated by @hey-api/openapi-ts

/**
 * ApiToken
 */
export type ApiToken = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Scope
   */
  scope: "read" | "write";
  /**
   * Prefix
   */
  prefix: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Expires At
   */
  expires_at?: string | null;
  /**
   * Last Used At
   */
  last_used_at?: string | null;
  [key: string]:
    | unknown
    | number
    | string
    | "read"
    | "write"
    | string
    | null
    | string
    | null
    | undefined;
};

/**
 * ApiTokenCreate
 */
export type ApiTokenCreate = {
  /**
   * Name
   */
  name?: string;
  /**
   * Scope
   */
  scope?: "read" | "write";
  /**
   * Days
   * 0: never expires
   */
  days?: number;
};

/**
 * ApiTokenCreated
 */
export type ApiTokenCreated = {
  /**
   * Id
   */
  id: number;
  /**
   * Token
   */
  token: string;
  /**
   * Note
   */
  note?: string;
  [key: string]: unknown | number | string | undefined;
};

/**
 * AuthStatus
 */
export type AuthStatus = {
  /**
   * Setup Required
   */
  setup_required: boolean;
  [key: string]: unknown | boolean;
};

/**
 * ForgotPasswordRequest
 */
export type ForgotPasswordRequest = {
  /**
   * Email
   */
  email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Me
 */
export type Me = {
  user: UserPublic;
  /**
   * Roles
   * namespace name -> role
   */
  roles: {
    [key: string]: "viewer" | "editor" | "owner";
  };
  /**
   * Via
   */
  via: "access" | "token";
  /**
   * Scope
   */
  scope: "read" | "write";
  [key: string]:
    | unknown
    | UserPublic
    | {
        [key: string]: "viewer" | "editor" | "owner";
      }
    | "access"
    | "token"
    | "read"
    | "write";
};

/**
 * Ok
 */
export type Ok = {
  /**
   * Ok
   */
  ok?: boolean;
  [key: string]: unknown | boolean | undefined;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
  /**
   * Refresh Token
   */
  refresh_token: string;
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * SetupRequest
 */
export type SetupRequest = {
  /**
   * Code
   */
  code: string;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Name
   */
  name?: string | null;
};

/**
 * TokenPair
 */
export type TokenPair = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Refresh Token
   */
  refresh_token: string;
  /**
   * Token Type
   */
  token_type?: "bearer";
  /**
   * Expires In
   * seconds until the access token expires
   */
  expires_in: number;
  user: UserPublic;
  [key: string]: unknown | string | "bearer" | number | UserPublic | undefined;
};

/**
 * UserPublic
 */
export type UserPublic = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Admin
   */
  admin?: boolean;
  /**
   * Disabled
   */
  disabled?: boolean | null;
  /**
   * Created At
   */
  created_at?: string | null;
  /**
   * Last Login At
   */
  last_login_at?: string | null;
  [key: string]:
    | unknown
    | number
    | string
    | string
    | null
    | boolean
    | boolean
    | null
    | string
    | null
    | string
    | null
    | undefined;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type StatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/status";
};

export type StatusResponses = {
  /**
   * Successful Response
   */
  200: AuthStatus;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type SetupData = {
  body: SetupRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/setup";
};

export type SetupErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetupError = SetupErrors[keyof SetupErrors];

export type SetupResponses = {
  /**
   * Successful Response
   */
  200: TokenPair;
};

export type SetupResponse = SetupResponses[keyof SetupResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: TokenPair;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshData = {
  body: RefreshRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/refresh";
};

export type RefreshErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
  /**
   * Successful Response
   */
  200: TokenPair;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
  body: RefreshRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type LogoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Successful Response
   */
  200: Ok;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type MeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type MeResponses = {
  /**
   * Successful Response
   */
  200: Me;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ForgotPasswordData = {
  body: ForgotPasswordRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/password/forgot";
};

export type ForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ForgotPasswordError =
  ForgotPasswordErrors[keyof ForgotPasswordErrors];

export type ForgotPasswordResponses = {
  /**
   * Successful Response
   */
  200: Ok;
};

export type ForgotPasswordResponse =
  ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
  body: ResetPasswordRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/password/reset";
};

export type ResetPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: Ok;
};

export type ResetPasswordResponse =
  ResetPasswordResponses[keyof ResetPasswordResponses];

export type ListTokensData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/tokens";
};

export type ListTokensResponses = {
  /**
   * Response Tokens-List Tokens
   * Successful Response
   */
  200: Array<ApiToken>;
};

export type ListTokensResponse = ListTokensResponses[keyof ListTokensResponses];

export type CreateTokenData = {
  body: ApiTokenCreate;
  path?: never;
  query?: never;
  url: "/api/v1/tokens";
};

export type CreateTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTokenError = CreateTokenErrors[keyof CreateTokenErrors];

export type CreateTokenResponses = {
  /**
   * Successful Response
   */
  200: ApiTokenCreated;
};

export type CreateTokenResponse =
  CreateTokenResponses[keyof CreateTokenResponses];

export type RevokeTokenData = {
  body?: never;
  path: {
    /**
     * Token Id
     */
    token_id: number;
  };
  query?: never;
  url: "/api/v1/tokens/{token_id}";
};

export type RevokeTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RevokeTokenError = RevokeTokenErrors[keyof RevokeTokenErrors];

export type RevokeTokenResponses = {
  /**
   * Successful Response
   */
  200: Ok;
};

export type RevokeTokenResponse =
  RevokeTokenResponses[keyof RevokeTokenResponses];

export type ClientOptions = {
  baseUrl: `${string}://openapi.json` | (string & {});
};
