# Makefile

BACKEND_DIR=fastapi_backend
FRONTEND_DIR=nextjs-frontend
DOCKER_COMPOSE=docker compose

.PHONY: help
help: ## List the commands
	@awk '/^[a-zA-Z_-]+:.*##/{split($$1, target, ":"); print "  " target[1] "\t" substr($$0, index($$0,"##")+3)}' $(MAKEFILE_LIST)

# Local development
.PHONY: start-backend test-backend lint-backend start-frontend test-frontend lint-frontend openapi worker docs

start-backend: ## Start the API with hot reload (and the OpenAPI watcher)
	cd $(BACKEND_DIR) && ./start.sh

worker: ## Run a job worker against the configured database
	cd $(BACKEND_DIR) && uv run lens worker

test-backend: ## Run the backend tests
	cd $(BACKEND_DIR) && uv run pytest -n auto

lint-backend: ## Lint, format check and type check the backend
	cd $(BACKEND_DIR) && uv run ruff check . && uv run ruff format --check . && uv run mypy

start-frontend: ## Start the web app with hot reload
	cd $(FRONTEND_DIR) && ./start.sh

test-frontend: ## Run the frontend tests
	cd $(FRONTEND_DIR) && pnpm run test

lint-frontend: ## Lint and type check the frontend
	cd $(FRONTEND_DIR) && pnpm run lint && pnpm run tsc

openapi: ## Regenerate the OpenAPI schema and the frontend client
	cd $(BACKEND_DIR) && uv run python -m commands.generate_openapi_schema
	cd $(FRONTEND_DIR) && pnpm run generate-client

docs: ## Serve the documentation
	cd $(BACKEND_DIR) && uv run mkdocs serve -f ../mkdocs.yml

# Run it (Docker)
PROD_COMPOSE=$(DOCKER_COMPOSE) -f docker-compose.prod.yml
.PHONY: run dev stop setup-code logs

run: export LENS_TARGET ?= full
run: .env ## Build once and run the whole stack, no hot reload (the fast way to use it): http://localhost:3000
	$(PROD_COMPOSE) up -d --build
	@echo "Lens is at http://localhost:3000. First start: 'make setup-code' for the admin setup code; 'make logs' to follow; 'make stop' to stop."

dev: ## Run the stack with hot reload (slower: pages compile on first visit)
	$(DOCKER_COMPOSE) up --build

stop: ## Stop whichever stack is running; the database and the archive stay in their volumes
	$(PROD_COMPOSE) down
	$(DOCKER_COMPOSE) down

setup-code: ## The first-admin setup code, from the backend log (only until the first account exists)
	@($(PROD_COMPOSE) logs backend 2>/dev/null; $(DOCKER_COMPOSE) logs backend 2>/dev/null) | grep -i "setup code" | tail -1 || true

logs: ## Follow the logs of whichever stack is running
	@$(PROD_COMPOSE) ps -q 2>/dev/null | grep -q . && $(PROD_COMPOSE) logs -f || $(DOCKER_COMPOSE) logs -f

.env: ## Secrets for `make run`, generated once (keep it: changing ACCESS_SECRET_KEY signs everyone out, ARCHIVE_SECRET_KEY makes stored credentials unreadable)
	@printf '# Generated by `make run`. Keep it with the volumes.\nACCESS_SECRET_KEY=%s\nARCHIVE_SECRET_KEY=%s\nAUTH_SECRET=%s\n# SurrealDB root password: set before the database volume is first created, and before exposing the port.\nSURREAL_PASS=root\n' "$$(openssl rand -hex 32)" "$$(openssl rand -hex 32)" "$$(openssl rand -hex 32)" > .env
	@echo "wrote .env with new secrets"

# Docker, piece by piece
.PHONY: docker-up docker-build docker-backend-shell docker-frontend-shell docker-test-backend docker-test-frontend docker-logs-setup

docker-up: ## Start the hot-reload stack without rebuilding
	$(DOCKER_COMPOSE) up

docker-build: ## Build all the images
	$(DOCKER_COMPOSE) build

docker-backend-shell: ## A shell in the backend container
	$(DOCKER_COMPOSE) run --rm backend sh

docker-frontend-shell: ## A shell in the frontend container
	$(DOCKER_COMPOSE) run --rm frontend sh

docker-test-backend: ## Run the backend tests in Docker
	$(DOCKER_COMPOSE) run --rm backend pytest

docker-test-frontend: ## Run the frontend tests in Docker
	$(DOCKER_COMPOSE) run --rm frontend pnpm run test

docker-logs-setup: ## Show the first-admin setup code
	$(DOCKER_COMPOSE) logs backend | grep -i "setup code"
