"""Every /api/v1 route, one module per area."""

from fastapi import APIRouter

from app.api.v1.routes import (
    admin,
    auth,
    batches,
    chats,
    collections,
    comments,
    content_types,
    entities,
    fields,
    files,
    hierarchy,
    iiif,
    imports,
    jobs,
    metadata,
    namespaces,
    notes,
    notifications,
    pipelines,
    public,
    recordings,
    requests,
    routines,
    search,
    searches,
    setup,
    sources,
    speakers,
    templates,
    uploads,
    users,
    video,
    views,
    workflows,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(auth.tokens)
for module in (
    users,
    admin,
    setup,
    namespaces,
    hierarchy,
    recordings,
    notes,
    comments,
    files,
    fields,
    imports,
    uploads,
    search,
    searches,
    speakers,
    entities,
    metadata,
    video,
    iiif,
    jobs,
    sources,
    templates,
    pipelines,
    content_types,
    workflows,
    chats,
    collections,
    batches,
    public,
    requests,
    views,
    notifications,
    routines,
):
    api_router.include_router(module.router)
